spring:
  config:
    additional-location: config/
  profiles:
    active: local
#    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com.daon.backend.auth.infrastructure: debug
    com.daon.backend.security: debug
    com.daon.backend.notification.infrastructure: debug
    com.daon.backend.mail.infrastructure: debug
