version: '3.7'

services:
   daon-db:
      container_name: daon-db
      image: postgres
      ports:
         - "5432:5432"
      volumes:
         - ./db/data:/var/lib/postgresql/data
      env_file: .env
      networks:
         default:
   daon-api:
      depends_on:
         - daon-db
      container_name: daon-api
      build: ../../
      ports:
         - "8080:8080"
      environment:
         TZ: Asia/Seoul
         spring.profiles.active: local
         spring.jpa.hibernate.ddl-auto: create
         spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/local_db
      networks:
         default:
